kind: pipeline
name: default

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - pip install -r dev-requirements.txt
  - which make || apk add make
  - make test
- name: build
  image: python:3.7-alpine
  commands:
  - which make || apk add make
  - which zip || apk add zip
  - make build
- name: upload
  image: python:3.7-alpine
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_key
  commands:
  - which make || apk add make
  - which aws || pip install awscli
  - make upload
  when:
    event:
    - tag
